### ISSUE TITLE
paf to las?

### ISSUE THREAD

**Issue by ilanshom** [lh3/minimap#12]
Hi, I am one of the developers of [HINGE](github.com/HingeAssembler/HINGE) and we would like to integrate minimap into our pipeline. But we currently work with .las files for the alignments. We noticed that a da2paf converter was discussed [here](https://github.com/lh3/miniasm/issues/3). So we were wondering if any .paf to .las converter has been written. Thanks!

**Comment by lh3** [comment]
.las is a binary format without a spec. It seems not a standalone format as it depends on the read database. Generating .las will be a lot harder than the reverse.

**Comment by govinda-kamath** [comment]
Do you have any script to convert paf to sam? You do seem to have a script to to do the reverse [here](https://github.com/lh3/miniasm/blob/master/misc/sam2paf.js)

**Comment by lh3** [comment]
It is not possible to convert minimap PAF to SAM because minimap PAF doesn't compute CIGAR. It is possible to convert minimap2 PAF to SAM if the PAF is generated with CIGAR. However, for read overlapping, minimap2 does not recommend to compute CIGAR for the performance purpose.

**Comment by ilanshom** [comment]
Thank you for your responses.
